name: Trigger Word Count Pipeline

on:
  push:
    paths:
      - 'data.txt'
    branches:
      - main

jobs:
  deploy:
    uses: Georges034302/azure-aci-acr-workflow/.github/workflows/deploy.yml@main
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
      ACR_NAME: ${{ secrets.ACR_NAME }}
      RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
      
